"""
Django settings for weather_project project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*7+)+79n7r(tod!_co8qw=o02uqa&6&%&i)0*l=)uhe*$c+!j#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Ứng dụng của bạn
    'weather_app', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'weather_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Dòng quan trọng: Chỉ định rõ đường dẫn tới folder templates
        'DIRS': [BASE_DIR / 'weather_app' / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'weather_project.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'vi'  # Tiếng Việt
TIME_ZONE = 'Asia/Ho_Chi_Minh' # Giờ Việt Nam
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Cấu hình để Django tìm thấy file ảnh/css trong thư mục static của dự án
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CẤU HÌNH ĐĂNG NHẬP / ĐĂNG XUẤT ---

# Nếu người dùng chưa đăng nhập mà cố vào trang admin/profile, sẽ bị đá về trang này
LOGIN_URL = 'login'

# Đăng nhập thành công thì chuyển về trang chủ (tên là 'home' trong urls.py)
LOGIN_REDIRECT_URL = 'home' 

# Đăng xuất xong thì quay lại trang login
LOGOUT_REDIRECT_URL = 'login'


# --- CẤU HÌNH GỬI EMAIL (GMAIL SMTP) ---
# Bạn nhớ thay email và mật khẩu ứng dụng của bạn vào bên dưới

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# >>> THAY THÔNG TIN CỦA BẠN VÀO 2 DÒNG DƯỚI ĐÂY <<<
EMAIL_HOST_USER = 'tengicungduocma056@gmail.com' 
EMAIL_HOST_PASSWORD = 'rdeb rnzp jxxf zywr'  # Mật khẩu ứng dụng 16 ký tự (App Password)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')