# Generated by Django 5.2.8 on 2026-01-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alert_city',
            field=models.CharField(default='Hanoi', help_text='Thành phố nhận cảnh báo', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_alerts',
            field=models.BooleanField(default=True, help_text='Có nhận mail cảnh báo không?'),
        ),
    ]
