# Generated by Django 5.2.8 on 2026-01-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0005_userprofile_alert_lat_userprofile_alert_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='alert_lat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alert_lon',
        ),
    ]
