# Generated by Django 5.2.8 on 2026-01-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0006_remove_userprofile_alert_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alert_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alert_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
